$(document).ready(function(){
	$("button").click(function(){
		$("[name]").hide(function(){
			alert($("input").attr("type"));
		});
	});
	$(".button").click(function(){
		alert($("p").text());
		$("p").text($("p").html());
		$("h1").append($("p").html());
	});
});